### ISSUE TITLE
Бд

### ISSUE THREAD

**Issue by OITBsuir** [rondarchik/PracticeTask#2]
1. Переименовать названия таблиц в sneak camel case (нижнее подчеркивание и еще с маленькой буквы):  User_Role -> user_role
2. Уберите лишние табы, и в других местах:
![image](https://github.com/rondarchik/PracticeTask/assets/159944065/be04546e-5cd8-4f16-a532-ce90105445a0)
3. Простите, что придираюсь) пробелчик поставьте в похожих местах:
![image](https://github.com/rondarchik/PracticeTask/assets/159944065/ce56184b-c4e4-4179-964a-99275a83fadb)
4. В primery key добавить not null.
5. Давайте все таки уберем или логин или эмейл, пускай будет одно что нибудь.
6.  user_id -> id_user, FK_on_User -> fk_user. Поменять в похожих местах
7. В таблице user_role (многие ко многим) не хватает primery key.

**Comment by rondarchik** [comment]
Пофиксила
